language: python

python:
  - 2.7

sudo: false

notifications:
  email: false
 
# Setup anaconda and install packages
install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n fermi-env python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib astropy pytest pyyaml
  - source activate fermi-env
  - pip install healpy
  - python setup.py install
  - bash stinstall.sh force # Download and install the ST binaries
  - source travissetup.sh
  - source condasetup.sh

#  - source activate test-environment
#  - pip install healpy
#  - python setup.py install
#  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib astropy 
#  - pip install healpy
 
# Run test
script:
  - py.test
 
cache:
  directories:
  - $HOME/ScienceTools