language: python
sudo: false

notifications:
  email: false

matrix:
    include:

        - os: linux
          env: PYTHON_VERSION=2.7
               CONDA_DOWNLOAD=Miniconda-latest-Linux-x86_64.sh
        - os: linux
          env: PYTHON_VERSION=3.5
               CONDA_DOWNLOAD=Miniconda3-latest-Linux-x86_64.sh


# Setup anaconda and install packages
install:
  - wget http://repo.continuum.io/miniconda/$CONDA_DOWNLOAD -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n fermi-env python=$PYTHON_VERSION numpy scipy matplotlib astropy pytest pyyaml
  - source activate fermi-env
  - conda install -c openastronomy healpy wcsaxes
#  - pip install healpy
  - python setup.py install
  - bash stinstall.sh force # Download and install the ST binaries
  - source travissetup.sh
  - source condasetup.sh

#  - source activate test-environment
#  - pip install healpy
#  - python setup.py install
#  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib astropy 
#  - pip install healpy
 
# Run test
script:
  - py.test -vv -s
 
#cache:
#  directories:
#  - $HOME/ScienceTools