#----------------------------------------------------------------------------
# Logging
logging:

  # Set the fermiPy log level
  verbosity : 3

  # Set the STs chatter level
  chatter : 3

#----------------------------------------------------------------------------
# Parameters that control where files are written and the location of
# the analysis output directory
fileio:

  outdir : null
  scratchdir  : '/scratch'

#----------------------------------------------------------------------------
# Define input data files (FT1, FT2, LTCube)
data:

  evfile : /nfs/slac/g/ki/ki20/cta/mdwood/fermi/data/P8_SOURCE_V6/P8_SOURCE_V6_239557414_428903014_z100_r180_gti_ft1.lst
  scfile : /nfs/slac/g/ki/ki20/cta/mdwood/fermi/data/P8_SOURCE_V4/P8_P301_SOURCE_239557414_428903014_ft2.fits 
  ltcube : null

#----------------------------------------------------------------------------
# Binning
binning:

  roiwidth   : 5.0   # ROI width in deg
  binsz      : 0.2   # spatial bin size in deg
  binsperdec : 8     # nb energy bins per decade
  
#----------------------------------------------------------------------------
# Data selections
selection:

  emin    : 100
  emax    : 100000
  zmax    : 100
  evclass : 128
  evtype  : 3
  filter  : 'DATA_QUAL>0 && LAT_CONFIG==1' # gtmktime filter string

  # Set the ROI center to the coordinates of 'target'
  target : 'mkn421'

#----------------------------------------------------------------------------
# IRFs
gtlike:

  edisp : True
  edisp_disable : ['isodiff','galdiff']
  irfs : 'P8R2_SOURCE_V6'

#----------------------------------------------------------------------------
# Settings for ROI model
model:

  # Include catalog sources within this distance from the ROI center
  src_radius  : null

  # Include catalog sources within a box of the given width. This
  # parameter should be at least as large as roiwidth.
  src_roiwidth : 10.0

  galdiff  : '$GLAST_EXT/diffuseModels/v5r0/gll_iem_v06.fits'
  isodiff  : '$GLAST_EXT/diffuseModels/v5r0/iso_P8R2_SOURCE_V6_v06.txt'

  # List of catalogs from which sources will be drawn.
  catalogs : 
    - '3FGL'

#----------------------------------------------------------------------------
# This is the block of the configuration where analysis components
# are defined.
components: null
    
#----------------------------------------------------------------------------
# Settings for SED analysis
sed: {}

#----------------------------------------------------------------------------
# Settings for Extension analysis
extension : {}